### PR TITLE
Changed state management to context API & changed folder structure

### PR DESCRIPTION
**Pull request by stavlocker**
changing the folder structure and changing the state management from easy-peasy to context api

_Originally created by @Liron-Wassa in #21_

### CODE REVIEW

**Comment by stavlocker** [comment]
For the next time:

1. Open an issue for each PR/mission you're doing
2. Create a feature branch in this repo, DON'T FORK.
3. Always branch out of `develop` and not `master`, and merge into `develop`. `master` is the production branch that in the future will be automatically uploaded into production, so watch out for that.
4. Commit titles should be concise - short and descriptive. The commit description should not repeat the title, and can be blank.

Please read the [CONTRIBUTING](https://github.com/Lev-Echad/levechad-backend/blob/master/CONTRIBUTING.md) file, as it contains all these directions.

_Originally posted by @astar26, modified & extended by me_

**Comment by stavlocker** [comment]
@Liron-Wassa None of this seems to work on my machine - seems like you updated file names, but not the imports (case-sensitivity). 

```
./src/index.js
Cannot find file: 'App.js' does not match the corresponding name on disk: '.\src\components\App\app'.
```

Also, make the files consistently UpperCamelCase because some are lowerCamelCase which is odd - `create-react-app` seems to create UpperCamelCase files so I'd stick with that convention.

**Review by astar26 — CHANGES_REQUESTED** [review]
See changes requested by @stavlocker

**Review by astar26 — APPROVED** [review]
Approved

**Pull request merged**
